#  Template NodeJS Cloud serverless functions

#  This template allows you to validate your NodeJS code.
#  The workflow allows running tests and code linting on the default branch.

pipelines:
  branches:
    development:
      - step:
          caches:
            - node
          name: Deploy development branch Garments
          #deployment: /development on gcp 
          image: google/cloud-sdk:latest
          script:
              - apt-get update && apt-get install -y gettext-base
              - envsubst < sa-dollappnodejs.dist.json > service-account.json
              - gcloud auth activate-service-account --key-file=service-account.json
              - gcloud functions deploy martianrobots --runtime nodejs12 --trigger-http --project $GCP_DOLLAPPNODEJS_PROJECT_ID --region $GCP_DOLLAPPNODEJS_REGION
    master:
      - step:
          caches:
            - node
          name: Deploy master branch Garments
          #master: /production on gcp 
          image: google/cloud-sdk:latest
          script:
              - apt-get update && apt-get install -y gettext-base
              - envsubst < sa-dollappnodejs.dist.json > service-account.json
              - gcloud auth activate-service-account --key-file=service-account.json
              - gcloud functions deploy martianrobots --runtime nodejs12 --trigger-http --project $GCP_DOLLAPPNODEJS_PROJECT_ID --region $GCP_DOLLAPPNODEJS_REGION
          
